# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37291832dc7de4638ee4f67b87520ba183801baef07132c913f8f30bae163587de575e7241d48496a770dd07a0d5c9be06d83a4585dc6186501f4448a85ac2a4

test:
  secret_key_base: 34d1dcbe63a6c1c788aa6407a0042bf80436af9994df52d1a87ccb2c41f738254a262f86867243883eef8ca53ba923d205d395a76165a9fc5c64139ca15c7bb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  host: YOUR PRODUCTION HOST URL/IP HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>